services:
  weather:
    build: ./weather
    container_name: weather
    restart: always
    env_file:
      - ./weather/.env
    ports:
      - "8080:8080"
  client:
    build: ./client
    container_name: client
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "80:80"
    depends_on:
      - weather